version: "3"

services:
  wtw-app: &wtw-app
    build:
      dockerfile: "./docker/Dockerfile"
      context: "."
    image: devbox:latest
    environment: &wtw-app_env
      APP_HOST: "0.0.0.0"
      APP_PORT: 5001
      LOG_LEVEL: "debug"

      POSTGRES_USERNAME: "user"
      POSTGRES_PASSWORD: "Password"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: 5432
      POSTGRES_NAME: "postgres"

      MONGO_USERNAME: "user"
      MONGO_PASSWORD: "Password"
      MONGO_HOST: "mongodb"
      MONGO_PORT: 27017
      MONGO_NAME: "mongodb"
    tty: true
    depends_on:
      - postgres
      - mongodb
    ports:
      - "5001:5001"
    volumes:
      - ".:/app"

  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "Password"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/data/postgresData

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_DB: "mongodb"
      MONGO_USER: "user"
      MONGO_PASSWORD: "Password"
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/mongodbData

volumes:
  postgres-data:
  mongodb-data:
