version: "3"

services:
  wtw-app: &wtw-app
    build:
      dockerfile: "./docker/Dockerfile"
      context: "."
    image: devbox:latest
    environment: &wtw-app_env
      APP_HOST: "0.0.0.0"
      APP_PORT: 5001
      LOG_LEVEL: "debug"
      DB_USERNAME: "user"
      DB_PASSWORD: "Password"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_NAME: "database"
    tty: true
    depends_on:
      - database
    ports:
      - "5001:5001"
    volumes:
      - ".:/app"

  database:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: "database"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "Password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - db-vol:/var/lib/postgresql/data/pgdata

volumes:
  db-vol:
