FROM python:3.10

WORKDIR /app

ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y gcc python-dev
RUN apt-get install -y libpq-dev postgresql-client
RUN apt-get install -y wget \
    && wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.1.tar.gz \
    && rm dockerize-linux-amd64-v0.6.1.tar.gz

COPY ./requirements.txt ./
RUN pip install -U pip
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5001

COPY . .

CMD dockerize -timeout 120s -wait tcp://"${DB_HOST:-}":"${DB_PORT:-info}" && \
  python -m uvicorn WTW_app.app:app --log-level "${LOG_LEVEL:-info}" \
    --host "${APP_HOST:-0.0.0.0}" --port "${APP_PORT:-5001}" --reload "${@}"