FROM python:3.10

WORKDIR /app

ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y gcc python-dev
RUN apt-get install -y libpq-dev postgresql-client
RUN apt-get install -y wget \
    && wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.1.tar.gz \
    && rm dockerize-linux-amd64-v0.6.1.tar.gz 

# Install MongoDB client tools
RUN wget https://fastdl.mongodb.org/tools/db/mongodb-database-tools-debian10-x86_64-100.5.0.deb
RUN dpkg -i mongodb-database-tools-debian10-x86_64-100.5.0.deb
RUN rm mongodb-database-tools-debian10-x86_64-100.5.0.deb

COPY ./requirements.txt ./
RUN pip install -U pip
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5001

COPY . .

CMD dockerize -timeout 120s -wait tcp://"${POSTGRES_HOST:-}":"${POSTGRES_PORT:-info}" && \
  dockerize -timeout 120s -wait tcp://"${MONGO_HOST:-}":"${MONGO_PORT:-27017}" && \
  python -m uvicorn WTW_app.app:app --log-level "${LOG_LEVEL:-info}" \
    --host "${APP_HOST:-0.0.0.0}" --port "${APP_PORT:-5001}" --reload "${@}"